doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            Sitemap:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Sitemap/Domain'
                prefix: 'App\Sitemap\Domain'
                alias: Sitemap
            Blog:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Blog/Domain'
                prefix: 'App\Blog\Domain'
                alias: Blog
            Brand:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Brand/Domain'
                prefix: 'App\Brand\Domain'
                alias: Brand

when@test:
    doctrine:
        dbal:
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
